import { useState, useMemo } from 'react'
// memo를 써서 filter, pokemon 어디가 바뀌든 새로운 filter를 제공한다.
import Head from 'next/head'
import { useQuery, dehydrate, QueryClient } from 'react-query'
import styles from '../styles/Home.module.css'

interface Pokemon {
  id: number
  name: string
  image: string
}

const getPokemon = (): Promise<Pokemon[]> =>
  fetch('https://jherr-pokemon.s3.us-west-1.amazonaws.com/index.json').then(
    (resp) => resp.json()
  )

// serverside props function 함수명이 지정되어 있음.
// react-query 에서는 fetcher 가 필요해서 getPokemon fetch를 분리함.
export async function getServerSideProps() {
  const queryClient = new QueryClient()
  await queryClient.prefetchQuery('pokemon', getPokemon)

  return {
    props: {
      // initialPokemon: await getPokemon(),
      dehydratedState: dehydrate(queryClient),
    },
  }
}

// react-query 기본적인 사용법
// import { useQuery } from "react-query";
// // 주로 사용되는 3가지 return 값 외에도 더 많은 return 값들이 있다.
// const { data, isLoading, error } = useQuery(queryKey, queryFn, options)
export default function Home() {
  const { data: pokemon } = useQuery('pokemon', getPokemon, {
    // initialData: initialPokemon,
    refetchOnMount: false,
    refetchOnWindowFocus: false,
    // 두개의 옵션은 데이터가 stale해도 새로고침하면 refetch가 안됨.
  })

  const [filter, setFilter] = useState('')

  const filteredPokemon = useMemo(
    () =>
      pokemon.filter((p) =>
        p.name.toLowerCase().includes(filter.toLowerCase())
      ),
    [filter, pokemon]
    // filter, pokemon 둘 중 뭐가 바뀌어도 pokemon은 바뀌지 않아 리렌더링 되지 않음.
    // search 에 일반적인 useCase 임. 기억할 것.
  )
  return (
    <div className={styles.main}>
      <Head>
        <title>Pokemon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <input
          type="text"
          value={filter}
          onChange={(e) => setFilter(e.target.value)}
          className={styles.search}
        />
      </div>
      <div className={styles.container}>
        {filteredPokemon.slice(0, 20).map((p) => (
          <div key={p.id} className={styles.image}>
            <img
              src={`https://jherr-pokemon.s3.us-west-1.amazonaws.com/${p.image}`}
              alt="{p.name}"
            />
            <h2>{p.name}</h2>
          </div>
        ))}
      </div>
    </div>
  )
}
